### PR TITLE
Add support for pydantic v2

### PR DESCRIPTION
**Pull request by sharonyogev**
This add support for pydantic v2 without dropping support to pydantic v1
I would love this to be merged soon so I can upgrade pydantic in my project

### CODE REVIEW

**Comment by DaanRademaker** [comment]
Looking pretty good to me. Will ask some feedback from other maintainers as well.
For now, the isort check is failing so that needs to be fixed.

**Comment by sharonyogev** [comment]
Thanks, updated the isort problem 🙏 
BTW, note that since I added the pydantic-version to the version matrix, it failed to find the required check

**Review by timvancann — APPROVED** [review]
Looks good to me. Nice addition.

**Comment by timvancann** [comment]
@sharonyogev Just made a new release for you.
https://pypi.org/project/pydantic-avro/

**Comment by sharonyogev** [comment]
@timvancann I think you force push some commits that removed this merged PR...
Can you check, if you want me to rebase and re-open the PR tell me

**Pull request merged**
